# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/Brightcoders-Bootcamps/kata-05-secret-handshake-EdsonMorfin" }

# gem "rails"

gem 'rake'
gem 'rubycritic'
gem 'rubycritic-small-badge', :require => false
